/**
 * The letters themselves - who each is from, what she wrote, and the song that
 * goes with it - and the manifest of every picture the scene needs.
 *
 * Kept apart from `mail-art.ts` because this is content and that is geometry:
 * the words change often and the measurements almost never.
 */

import {
  ARROW,
  BABYS_BREATH,
  CONTENTS,
  DAISY,
  ENVELOPE,
  LILY,
  NAME_CARD,
  OPEN_BACK,
  OPEN_FRONT,
  PHOTO_ANNE,
  PHOTO_ANNY,
  PHOTO_BANK,
  PHOTO_BOY,
  PHOTO_NAMPHEUNG,
  PHOTO_NINA,
  PHOTO_SUMO,
  PHOTO_TIMMY,
  ROSE,
  SEAL,
  SUNFLOWER,
  TICKET,
  TULIP,
} from "@/lib/constants/mail-art";
import type { Letter } from "@/types/mails";

export const LETTERS: Letter[] = [
  {
    id: 1,
    slug: "one",
    prefix: "NAMPHEUNG",
    name: "Souphonesili",
    surname: "KEOMANT",
    colour: "red",
    seal: "pink",
    flower: ROSE,
    wish: [
      "Teacher Neung, you are the best teacher in my life.",
      "The first time I met you, you interviewed me and ",
      "believed in my ability to receive a scholarship. ",
      "I was 14 and didn’t know what a scholarship was.",
      "You guided me through my ups and downs.",
      "You made everything possible. At first, it was a ",
      "simple English class. But then you introduced me",
      "the ASEAN scholarship which opened up my eyes to",
      "the world of opportunities and quality education.",
      " ",
      " ",
      "Thank you for never leaving me alone. Without you,",
      "I would not have been a person who I am today.",
      "You didn’t only teach me how to be a scholar but",
      "also how to be a good and kind person. You teach",
      "us through your life lessons and never hind us",
      "from what you know. I am grateful to know you and",
      " be your student. My UWC experience never felt ",
      "like being left behind because you always encouraged",
      "me to study and be a better person every day.",
      "I learned from you how to be more disciplined and ",
      "goal-oriented. It’s a valuable and accessible lesson",
      "for us. You are incredibly smart, talented and",
      "kindhearted.",
      " ",
      "Love you so much teacher ",
      "🥰😍Happy Teacher’s Day 🤩, ",
      "I wish you all the best and hope you get to where",
      "you want and be happy in your life 😍 be healthy",
      "and wealthy 👏🏻",
    ],
    signed: "With love, Nampheung",
    song: {
      kind: "file",
      src: "/audio/tape-nampheung.m4a",
      title: "A message for you",
      by: "Nampheung",
    },
    postcard: {
      from: "Nampheung",
      address: ["Teacher Nueng", "wherever this finds you"],
      note: [
        "I took the long way round",
        "to say this, and then the",
        "card took longer still.",
        "",
        "Every room I have been",
        "taught in since has been",
        "measured against yours.",
        "",
        "Still your student.",
      ],
      photo: PHOTO_NAMPHEUNG,
    },
  },
  {
    id: 2,
    slug: "two",
    prefix: "ANNY",
    name: "Seankeo",
    surname: "XAICHALEUN",
    colour: "blue",
    seal: "silver",
    flower: LILY,
    wish: [
      "On Teacher’s Day, I just want to say thank you for",
      "always being such a wonderful teacher to me. ",
      "You’ve always guided us, taught us what’s best for ",
      "us, and supported us with nothing but kindness ",
      "and good intentions. I truly appreciate everything",
      "you’ve done for us and all the care you’ve shown ",
      "along the way.",
      "I wish you good health, less stress, and I hope ",
      "everything you wish for comes true. You deserve",
      "all the happiness and good things in life.",
      "",
      "",
    ],
    signed: "With love and respect, always. ❤️",
    song: {
      kind: "file",
      src: "/audio/tape-anny.mp3",
      title: "A message for you",
      by: "Anny",
    },
    postcard: {
      from: "Anny",
      address: ["Teacher Nueng", "with love, still"],
      note: [
        "I kept putting this off",
        "waiting for better words.",
        "There are none, so here",
        "are the ordinary ones -",
        "",
        "thank you. I remember",
        "all of it, even the parts",
        "you have surely forgotten.",
        "",
        "See you soon, I hope.",
      ],
      photo: PHOTO_ANNY,
    },
  },

  {
    id: 3,
    slug: "three",
    prefix: "BANK",
    name: "Vilaphon",
    surname: "MADMANIVONG",
    colour: "gold",
    seal: "bronze",
    flower: TULIP,
    wish: [
      "Well, I felt luckily that have met you even though",
      "just an accidentally searched in the google map",
      "honestly and saw a location called Home English.",
      "At first, my friend and I decided from some ",
      "pictures which showed in the application maybe ",
      "this place just taught only kids but in fact there",
      "was much more than our imagined, I still",
      "remembered well the first day that got into your",
      "class, that day was in reading lesson, so I ",
      "attempted to pronoun sounds of “Th” especially ",
      "Twentieth and Thirtieth were really tough for me",
      "but made me realized that there were nothing ",
      "easily to obtain, as you always say if something",
      "you get is free, you are a product to promote their ",
      "goods. However, throughout almost 4 years that ",
      "have been studied with you made me enjoyable ",
      "learning English just speak out to convert with a ",
      "stranger or friends without worries correct ",
      "grammar, Additionally, study here was opened up ",
      "a lot of opportunity for me not just only learn ",
      "English. For instance, being a volunteer as the ",
      "best milestone of mine because I could step out of ",
      "my comfort zone, had landed in others province to ",
      "expanding some soft skills to pupils over there. ",
      "Eventually, I was really thankful for everything that ",
      "you taught me if without you I would not have ",
      "been the person who am I today. Happy teacher’s ",
      "Day👩‍🏫🎁😊🥳",
    ],
    signed: "With love and respect, Bank",
    song: {
      kind: "file",
      src: "/audio/tape-bank.m4a",
      title: "A message for you",
      by: "Bank",
    },
    postcard: {
      from: "Bank",
      address: ["Teacher Nueng", "with love, still"],
      note: [
        "I kept putting this off",
        "waiting for better words.",
        "There are none, so here",
        "are the ordinary ones -",
        "",
        "thank you. I remember",
        "all of it, even the parts",
        "you have surely forgotten.",
        "",
        "See you soon, I hope.",
      ],
      photo: PHOTO_BANK,
    },
  },
  
  {
    id: 4,
    slug: "four",
    prefix: "Boy",
    name: "Boy",
    surname: "Sakonnavath",
    colour: "green",
    seal: "ivory",
    flower: DAISY,
    wish: [
      "Happy Teacher’s Day to my wonderful teachers!",
      "",
      "Thank you for teaching me and giving me ",
      "knowledge, advice, and encouragement. You ",
      "always help me when I do not understand",
      "something and encourage me to keep trying.",
      "",
      "I really appreciate your kindness, patience, and",
      "hard work. You are not only teachers, but also ",
      "people who help us become better and prepare us ",
      "for our future.",
      "",
      "On this special day, I wish all my teachers good",
      "health, happiness, success, and a wonderful life.",
      "Thank you for everything you have done for me.",
      "will always respect and appreciate you.",
      "",
    ],
    signed: "With respect and gratitude, Boy",
    song: {
      kind: "file",
      src: "/audio/tape-boy.m4a",
      title: "A message for you",
      by: "Boy",
    },
    postcard: {
      from: "Boy",
      address: ["Teacher Nueng", "with love, still"],
      note: [
        "I kept putting this off",
        "waiting for better words.",
        "There are none, so here",
        "are the ordinary ones -",
        "",
        "thank you. I remember",
        "all of it, even the parts",
        "you have surely forgotten.",
        "",
        "See you soon, I hope.",
      ],
      photo: PHOTO_BOY,
    },
  },

  {
    id: 5,
    slug: "five",
    prefix: "SUMO",
    name: "Mexay",
    surname: "PHAIPHITHOUN",
    colour: "purple",
    seal: "champagne",
    flower: SUNFLOWER,
    wish: [
      "Happy Teacher’s Day!",
      " ",
      "I want to say thank you for being a very important ",
      "teacher in my life. When I came to your class to ",
      "prepare for the scholarship, I thought I would only",
      "learn about scholarships. But you gave me much more",
      "than that. You taught me not only about studying,",
      "but also about life, how to think, make good choices,",
      "believe in myself, and become a better person everyday.",
      "Thank you for always helping me, giving me advice and",
      "believing in me. Now, I am enjoying my life, meeting",
      "new people, and having many new experiences. When I",
      "look back, I can see that I have changed a lot since",
      " I met you. Sometimes I think, I wish I had Known",
      "Teacher Nueng earlier.",
      "If I could choose one person in the world to be, I ",
      "would choose to be you. I admire how you always help ",
      "your students and want to see them succeed.",
      "I promise to take you as my role model. One day, I ",
      "want to help other people and help them reach their",
      "dreams, Just like you helped me.",
      "I wish you and everyone you love have good health, ",
      "happiness, and a wonderful life.",
      "The gift I want to give you is this simple letter",
      "and my best wishes. I hope every student you have ",
      "helped will be successful and reach their dreams.",
      "",
      "Thank you for everything, Teacher Nueng.",
      "I am truly grateful that I got to know you.",
      "",
    ],
    signed: "With respect and gratitude, Sumo",
    song: {
      kind: "youtube",
      id: "cL4uhaQ58Rk",
      title: "Lost Stars",
      by: "Adam Levine",
    },
    postcard: {
      from: "Sumo",
      address: ["Teacher Nueng", "with love, still"],
      note: [
        "I kept putting this off",
        "waiting for better words.",
        "There are none, so here",
        "are the ordinary ones -",
        "",
        "thank you. I remember",
        "all of it, even the parts",
        "you have surely forgotten.",
        "",
        "See you soon, I hope.",
      ],
      photo: PHOTO_SUMO,
    },
  },

  {
    id: 6,
    slug: "six",
    prefix: "NINA",
    name: "Lalita",
    surname: "THONGVANH",
    colour: "pink",
    seal: "wine",
    flower: SUNFLOWER,
    wish: [
      "Happy Teacher’s Day, dear Teacher Nueng! ",
      "Thank you for always dedicating your valuable",
      "time to teaching us. You have given me so much",
      "encouragement in my studies and helped me",
      "have a clearer goal for my future",
      "",
      "I sincerely wish you good health, happiness, and",
      "success in everything you wish for, including your",
      "career. May you always be happy and continue to ",
      "inspire many students. Thank you for everything ",
      "you have done for me. 💐❤️",
      
    ],
    signed: "Always yours, Nina",
    song: {
      kind: "youtube",
      id: "cL4uhaQ58Rk",
      title: "Lost Stars",
      by: "Adam Levine",
    },
    postcard: {
      from: "Nina",
      address: ["Teacher Nueng", "with love, still"],
      note: [
        "I kept putting this off",
        "waiting for better words.",
        "There are none, so here",
        "are the ordinary ones -",
        "",
        "thank you. I remember",
        "all of it, even the parts",
        "you have surely forgotten.",
        "",
        "See you soon, I hope.",
      ],
      photo: PHOTO_NINA,
    },
  },

  {
    id: 7,
    slug: "seven",
    prefix: "ANNE",
    name: "Anida",
    surname: "THONGVANH",
    colour: "pink",
    seal: "wine",
    flower: SUNFLOWER,
    wish: [
      "I do not think you ever knew how much",
      "you did. You were never only teaching",
      "the lesson on the board — you were",
      "teaching us that someone believed we",
      "would get there.",
      "",
      "Thank you for the second chances, and",
      "for never once making any of us feel",
      "small.",
      "",
      "Happy Teacher's Day, Teacher Nueng.",
      "Wherever we end up, a piece of you",
      "comes with us.",
    ],
    signed: "Always yours, Anne",
    song: {
      kind: "youtube",
      id: "cL4uhaQ58Rk",
      title: "Lost Stars",
      by: "Adam Levine",
    },
    postcard: {
      from: "Anne",
      address: ["Teacher Nueng", "with love, still"],
      note: [
        "I kept putting this off",
        "waiting for better words.",
        "There are none, so here",
        "are the ordinary ones -",
        "",
        "thank you. I remember",
        "all of it, even the parts",
        "you have surely forgotten.",
        "",
        "See you soon, I hope.",
      ],
      photo: PHOTO_ANNE,
    },
  },

  /* The last letter, and the way to the end credits: it holds a ticket to the
     museum where the others hold a cassette. */
  {
    id: 8,
    slug: "eight",
    prefix: "Timmy",
    name: "Visaithat",
    surname: "PHATHITMYXAY",
    colour: "white",
    seal: "yellow",
    flower: BABYS_BREATH,
    holds: [CONTENTS[0], CONTENTS[1], TICKET],
    wish: [
      "I’ve been thinking about how to say this, and",
      "honestly, “thank you” doesn’t feel like enough.",
      "",
      "You were not just my English teacher. You were",
      "one of the people who helped me believe in myself",
      "and gave me the confidence to try things I once",
      "thought were impossible.",
      "",
      "I still remember your advice that encouraged me",
      "to apply for a software developer job. At that",
      "time, I wasn’t sure if I was good enough, but you",
      "helped me become brave enough to try. 😅",
      "",
      "And now, I’m really happy to tell you that I",
      "achieved one of my biggest goals. I received a",
      "fully funded scholarship in Vietnam to study",
      "Artificial Intelligence and Computer Science!",
      "🎓🇻🇳",
      "",
      "I’ve also grown so much along the way. I can now",
      "build my own websites from scratch. For example,",
      "I recently spent a whole month creating this",
      "website with J Anne. It might sound simple, but",
      "for me, it represents how far I’ve come.",
      "",
      "Looking back, I realize that you didn’t just teach",
      "me English. You were the fire that lit my candle,",
      "filling it with motivation, confidence, and the",
      "strength to never give up.",
      "",
      "Thank you for believing in me before I fully",
      "believed in myself.",
      "",
      "I hope that one day, when I become a successful",
      "software developer or AI engineer, I can look back",
      "and say, “Teacher Nueng was one of the people who",
      "helped me become who I am.”",
      "",
      "And don’t worry, I won’t forget my English teacher",
      "when I become famous. 😂",
    ],
    signed: "With love and gratitude, Timmy ❤️",
    postcard: {
      from: "Timmy",
      address: ["Teacher Nueng", "my English teacher"],
      note: [
        "Thank you for everything.",
        "",
        "Don't forget to click the",
        "ticket to visit the End",
        "Credits Museum!",
      ],
      photo: PHOTO_TIMMY,
    },
  },
];

/** Every image the scene needs before it can play its opening. */
export const MAIL_SOURCES: readonly string[] = [
  ENVELOPE.src,
  OPEN_BACK.src,
  OPEN_FRONT.src,
  ...CONTENTS.map((item) => item.src),
  TICKET.src,
  NAME_CARD.src,
  SEAL.src,
  ...LETTERS.map((letter) => letter.flower.src),
  /* Not shown until the envelope is open, but fetched with the rest: it arrives
     as a mask, and a mask that has not loaded is not a blank arrow — it is no
     mask at all, which paints the whole box in ink. */
  ARROW.src,
];
