/**
 * The letters themselves - who each is from, what she wrote, and the song that
 * goes with it - and the manifest of every picture the scene needs.
 *
 * Kept apart from `mail-art.ts` because this is content and that is geometry:
 * the words change often and the measurements almost never.
 */

import {
  ARROW,
  BABYS_BREATH,
  CHRYSANTHEMUM,
  CONTENTS,
  DAISY,
  ENVELOPE,
  LILY,
  LILY_OF_THE_VALLEY,
  NAME_CARD,
  OPEN_BACK,
  OPEN_FRONT,
  ORCHID_DAFFODIL,
  PHOTO_ANNE,
  PHOTO_ANNIE,
  PHOTO_ANNY,
  PHOTO_BAIFERN,
  PHOTO_BANK,
  PHOTO_BOY,
  PHOTO_MINT,
  PHOTO_NAMPHEUNG,
  PHOTO_NINA,
  PHOTO_SOUTHIPHON,
  PHOTO_SUMO,
  PHOTO_TIMMY,
  RED_TULIP,
  ROSE,
  SEAL,
  SNOWDROP_LILY,
  SUNFLOWER,
  TICKET,
  TULIP,
} from "@/lib/constants/mail-art";
import type { Letter } from "@/types/mails";

export const LETTERS: Letter[] = [
  {
    id: 1,
    slug: "one",
    prefix: "NAMPHEUNG",
    name: "Souphonesili",
    surname: "KEOMANT",
    colour: "red",
    seal: "pink",
    flower: ROSE,
    wish: [
      "Teacher Neung, you are the best teacher in my life.",
      "The first time I met you, you interviewed me and ",
      "believed in my ability to receive a scholarship. ",
      "I was 14 and didn’t know what a scholarship was.",
      "You guided me through my ups and downs.",
      "You made everything possible. At first, it was a ",
      "simple English class. But then you introduced me",
      "the ASEAN scholarship which opened up my eyes to",
      "the world of opportunities and quality education.",
      " ",
      " ",
      "Thank you for never leaving me alone. Without you,",
      "I would not have been a person who I am today.",
      "You didn’t only teach me how to be a scholar but",
      "also how to be a good and kind person. You teach",
      "us through your life lessons and never hind us",
      "from what you know. I am grateful to know you and",
      " be your student. My UWC experience never felt ",
      "like being left behind because you always encouraged",
      "me to study and be a better person every day.",
      "I learned from you how to be more disciplined and ",
      "goal-oriented. It’s a valuable and accessible lesson",
      "for us. You are incredibly smart, talented and",
      "kindhearted.",
      " ",
      "Love you so much teacher ",
      "🥰😍Happy Teacher’s Day 🤩, ",
      "I wish you all the best and hope you get to where",
      "you want and be happy in your life 😍 be healthy",
      "and wealthy 👏🏻",
    ],
    signed: "With love, Nampheung",
    song: {
      kind: "file",
      src: "/audio/tape-nampheung.m4a",
      title: "A message for you",
      by: "Nampheung",
    },
    postcard: {
      from: "Nampheung",
      address: ["Teacher Nueng", "wherever this finds you"],
      note: [
        "I took the long way round",
        "to say this, and then the",
        "card took longer still.",
        "",
        "Every room I have been",
        "taught in since has been",
        "measured against yours.",
        "",
        "Still your student.",
      ],
      photo: PHOTO_NAMPHEUNG,
    },
  },
  {
    id: 2,
    slug: "two",
    prefix: "ANNY",
    name: "Seankeo",
    surname: "XAICHALEUN",
    colour: "blue",
    seal: "silver",
    flower: LILY,
    wish: [
      "On Teacher’s Day, I just want to say thank you for",
      "always being such a wonderful teacher to me. ",
      "You’ve always guided us, taught us what’s best for ",
      "us, and supported us with nothing but kindness ",
      "and good intentions. I truly appreciate everything",
      "you’ve done for us and all the care you’ve shown ",
      "along the way.",
      "I wish you good health, less stress, and I hope ",
      "everything you wish for comes true. You deserve",
      "all the happiness and good things in life.",
      "",
      "",
    ],
    signed: "With love and respect, always. ❤️",
    song: {
      kind: "file",
      src: "/audio/tape-anny.mp3",
      title: "A message for you",
      by: "Anny",
    },
    postcard: {
      from: "Anny",
      address: ["Teacher Nueng", "with love, still"],
      note: [
        "I kept putting this off",
        "waiting for better words.",
        "There are none, so here",
        "are the ordinary ones -",
        "",
        "thank you. I remember",
        "all of it, even the parts",
        "you have surely forgotten.",
        "",
        "See you soon, I hope.",
      ],
      photo: PHOTO_ANNY,
    },
  },

  {
    id: 3,
    slug: "three",
    prefix: "BANK",
    name: "Vilaphon",
    surname: "MADMANIVONG",
    colour: "gold",
    seal: "bronze",
    flower: TULIP,
    wish: [
      "Well, I felt luckily that have met you even though",
      "just an accidentally searched in the google map",
      "honestly and saw a location called Home English.",
      "At first, my friend and I decided from some ",
      "pictures which showed in the application maybe ",
      "this place just taught only kids but in fact there",
      "was much more than our imagined, I still",
      "remembered well the first day that got into your",
      "class, that day was in reading lesson, so I ",
      "attempted to pronoun sounds of “Th” especially ",
      "Twentieth and Thirtieth were really tough for me",
      "but made me realized that there were nothing ",
      "easily to obtain, as you always say if something",
      "you get is free, you are a product to promote their ",
      "goods. However, throughout almost 4 years that ",
      "have been studied with you made me enjoyable ",
      "learning English just speak out to convert with a ",
      "stranger or friends without worries correct ",
      "grammar, Additionally, study here was opened up ",
      "a lot of opportunity for me not just only learn ",
      "English. For instance, being a volunteer as the ",
      "best milestone of mine because I could step out of ",
      "my comfort zone, had landed in others province to ",
      "expanding some soft skills to pupils over there. ",
      "Eventually, I was really thankful for everything that ",
      "you taught me if without you I would not have ",
      "been the person who am I today. Happy teacher’s ",
      "Day👩‍🏫🎁😊🥳",
    ],
    signed: "With love and respect, Bank",
    song: {
      kind: "file",
      src: "/audio/tape-bank.m4a",
      title: "A message for you",
      by: "Bank",
    },
    postcard: {
      from: "Bank",
      address: ["Teacher Nueng", "with love, still"],
      note: [
        "I kept putting this off",
        "waiting for better words.",
        "There are none, so here",
        "are the ordinary ones -",
        "",
        "thank you. I remember",
        "all of it, even the parts",
        "you have surely forgotten.",
        "",
        "See you soon, I hope.",
      ],
      photo: PHOTO_BANK,
    },
  },
  
  {
    id: 4,
    slug: "four",
    prefix: "Boy",
    name: "Boy",
    surname: "Sakonnavath",
    colour: "green",
    seal: "ivory",
    flower: DAISY,
    wish: [
      "Happy Teacher’s Day to my wonderful teachers!",
      "",
      "Thank you for teaching me and giving me ",
      "knowledge, advice, and encouragement. You ",
      "always help me when I do not understand",
      "something and encourage me to keep trying.",
      "",
      "I really appreciate your kindness, patience, and",
      "hard work. You are not only teachers, but also ",
      "people who help us become better and prepare us ",
      "for our future.",
      "",
      "On this special day, I wish all my teachers good",
      "health, happiness, success, and a wonderful life.",
      "Thank you for everything you have done for me.",
      "will always respect and appreciate you.",
      "",
    ],
    signed: "With respect and gratitude, Boy",
    song: {
      kind: "file",
      src: "/audio/tape-boy.m4a",
      title: "A message for you",
      by: "Boy",
    },
    postcard: {
      from: "Boy",
      address: ["Teacher Nueng", "with love, still"],
      note: [
        "I kept putting this off",
        "waiting for better words.",
        "There are none, so here",
        "are the ordinary ones -",
        "",
        "thank you. I remember",
        "all of it, even the parts",
        "you have surely forgotten.",
        "",
        "See you soon, I hope.",
      ],
      photo: PHOTO_BOY,
    },
  },

  {
    id: 5,
    slug: "five",
    prefix: "SUMO",
    name: "Mexay",
    surname: "PHAIPHITHOUN",
    colour: "purple",
    seal: "champagne",
    flower: SUNFLOWER,
    wish: [
      "Happy Teacher’s Day!",
      " ",
      "I want to say thank you for being a very important ",
      "teacher in my life. When I came to your class to ",
      "prepare for the scholarship, I thought I would only",
      "learn about scholarships. But you gave me much more",
      "than that. You taught me not only about studying,",
      "but also about life, how to think, make good choices,",
      "believe in myself, and become a better person everyday.",
      "Thank you for always helping me, giving me advice and",
      "believing in me. Now, I am enjoying my life, meeting",
      "new people, and having many new experiences. When I",
      "look back, I can see that I have changed a lot since",
      " I met you. Sometimes I think, I wish I had Known",
      "Teacher Nueng earlier.",
      "If I could choose one person in the world to be, I ",
      "would choose to be you. I admire how you always help ",
      "your students and want to see them succeed.",
      "I promise to take you as my role model. One day, I ",
      "want to help other people and help them reach their",
      "dreams, Just like you helped me.",
      "I wish you and everyone you love have good health, ",
      "happiness, and a wonderful life.",
      "The gift I want to give you is this simple letter",
      "and my best wishes. I hope every student you have ",
      "helped will be successful and reach their dreams.",
      "",
      "Thank you for everything, Teacher Nueng.",
      "I am truly grateful that I got to know you.",
      "",
    ],
    signed: "With respect and gratitude, Sumo",
    song: {
      kind: "file",
      src: "/audio/tape-mexay.m4a",
      title: "A message for you",
      by: "Sumo",
    },
    postcard: {
      from: "Sumo",
      address: ["Teacher Nueng", "with love, still"],
      note: [
        "I kept putting this off",
        "waiting for better words.",
        "There are none, so here",
        "are the ordinary ones -",
        "",
        "thank you. I remember",
        "all of it, even the parts",
        "you have surely forgotten.",
        "",
        "See you soon, I hope.",
      ],
      photo: PHOTO_SUMO,
    },
  },

  {
    id: 6,
    slug: "six",
    prefix: "NINA",
    name: "Lalita",
    surname: "THONGVANH",
    colour: "pink",
    seal: "wine",
    flower: SUNFLOWER,
    wish: [
      "Happy Teacher’s Day, dear Teacher Nueng! ",
      "Thank you for always dedicating your valuable",
      "time to teaching us. You have given me so much",
      "encouragement in my studies and helped me",
      "have a clearer goal for my future",
      "",
      "I sincerely wish you good health, happiness, and",
      "success in everything you wish for, including your",
      "career. May you always be happy and continue to ",
      "inspire many students. Thank you for everything ",
      "you have done for me. 💐❤️",
      
    ],
    signed: "Always yours, Nina",
    song: {
      kind: "file",
      src: "/audio/tape-nina.m4a",
      title: "A message for you",
      by: "Nina",
    },
    postcard: {
      from: "Nina",
      address: ["Teacher Nueng", "with love, still"],
      note: [
        "I kept putting this off",
        "waiting for better words.",
        "There are none, so here",
        "are the ordinary ones -",
        "",
        "thank you. I remember",
        "all of it, even the parts",
        "you have surely forgotten.",
        "",
        "See you soon, I hope.",
      ],
      photo: PHOTO_NINA,
    },
  },

  {
    id: 7,
    slug: "seven",
    prefix: "ANNE",
    name: "Anida",
    surname: "THONGVANH",
    colour: "pink",
    seal: "wine",
    flower: LILY_OF_THE_VALLEY,
    wish: [
      "You are not just a teacher, but a truly strong,",
      "dedicated, and inspiring woman.",
      "",
      "Thinking back to when I started chasing my",
      "dreams, you were the person who truly believed in",
      "me you even told me I’d make it like you saw it",
      "already, even when that time, I don’t even",
      "realize my ability. It’s not just me, you give",
      "that same support and care to all of your",
      "students. We used to joke that you must love us",
      "as if we were your own children! Hahaha",
      "",
      "During my time in Australia, I made some mistakes",
      "and felt so down. In those moments, your advice",
      "and warnings would echo in my mind. At first, I",
      "blamed myself: ‘How could I make this mistake",
      "when you’ve been warning me?’ But then I",
      "realized, if I were to tell you about it, you",
      "would probably tell me that this mistake is just",
      "another way to make this the lessons deep into my",
      "heart so I will never repeat it. See, you really",
      "have an influence on my life. Just imagining",
      "telling you the thing already helps me find all",
      "my own answers! Hahaha.",
      "",
      "Anyways, I wish your days would be filled with",
      "warmth, joy and happiness, let go of every",
      "worries and may never concerns be come truth.",
      "Wishing you success, be healthy and wealthy.",
      "Thank you for being our guiding star.",
    ],
    signed: "With love and thunder, Anne",
    song: {
      kind: "youtube",
      id: "cL4uhaQ58Rk",
      title: "Lost Stars",
      by: "Adam Levine",
    },
    postcard: {
      from: "Anne",
      address: ["Teacher Nueng", "with love, still"],
      note: [
        "I kept putting this off",
        "waiting for better words.",
        "There are none, so here",
        "are the ordinary ones -",
        "",
        "thank you. I remember",
        "all of it, even the parts",
        "you have surely forgotten.",
        "",
        "See you soon, I hope.",
      ],
      photo: PHOTO_ANNE,
    },
  },

  {
    id: 9,
    slug: "nine",
    prefix: "MINT",
    name: "Sunida",
    surname: "VONGVANDALAT",
    colour: "mint",
    seal: "brown",
    flower: SNOWDROP_LILY,
    wish: [
      "I want to thank you for everything you have",
      "taught me and for never giving up on me since I",
      "was a child. I didn’t always study English hard,",
      "but every time, you would support me. I have",
      "studied with you for a long time, and I will keep",
      "studying with you.",
      "",
      "I don’t have enough words to say how much I want",
      "to thank you at this moment. Now, I understand",
      "English better, but not everything. But you can",
      "always fix my loopholes and explain things to me.",
      "Now, I think I am better than before because I",
      "studied harder with you and Before I moved up",
      "from Grade 9 to Grade 10, my mindset changed. I",
      "realized that I have to practice by myself and",
      "focus on my future. At that moment, I thought I",
      "had to study because I wanted to speak English",
      "well and improve my other skills. It may not be",
      "enough, but I think it is good enough for me now,",
      "and I will keep practicing and improving.",
      "",
      "Now, you are like sunshine that makes me want to",
      "study English. You changed my mindset about",
      "studying and made me want to become better. Now,",
      "I choose to put my studies first, not only",
      "English but other subjects too.",
      "",
      "I want to wish you to be happy with your family,",
      "your future, your work, and anything you hope to",
      "accomplish. 😊",
      "",
      "Thanks again, Teacher Neung.",
    ],
    signed: "With love, Mint",
    song: {
      kind: "file",
      src: "/audio/tape-mint.ogg",
      title: "A message for you",
      by: "Mint",
    },
    postcard: {
      from: "Mint",
      address: ["Teacher Nueng", "my sunshine teacher"],
      note: [
        "Thank you for everything,",
        "Teacher Nueng.",
        "",
        "Happy Teacher’s Day!",
      ],
      photo: PHOTO_MINT,
    },
  },

  {
    id: 10,
    slug: "ten",
    prefix: "SOUTHIPHON",
    name: "Southiphon",
    surname: "VONGVANDALAT",
    colour: "red",
    seal: "yellow",
    flower: ORCHID_DAFFODIL,
    wish: [
      "For more than half of my life that I have been",
      "your student and I can totally say that you are",
      "the best teacher I’ve ever known. When I look",
      "back on all these years, I just feel incredibly",
      "lucky and glad to have been your student.",
      "",
      "You taught me English when I couldn’t even say",
      "“What’s your name?” right, and instead of giving",
      "up on me, you tried your best to find ways to",
      "improve my English, and it worked. Looking back",
      "at how I first started and how I am now, I can",
      "see how much I’ve grown and how effective your",
      "ways are.",
      "",
      "And you didn’t only teach me English. You also",
      "inspired me to be a bassist. I used to think that",
      "I couldn’t do anything well except studying",
      "because that’s what everyone said, which also",
      "made me think that maybe I was like everyone",
      "said. But because of you, you made me wanted to",
      "try something new and I can actually do something",
      "else like playing an instrument which is a bass",
      "guitar, I also have a thought of playing a guitar",
      "if i can afford it lol.",
      "",
      "And most importantly I wanna thank you for",
      "everything you’ve done for me and everything",
      "you’ve taught me and for inspiring me. And i hope",
      "you will keep inspiring people around you like",
      "you have inspired me.🙏♥️",
    ],
    signed: "With love, Southiphon",
    song: {
      kind: "file",
      src: "/audio/tape-southiphon.ogg",
      title: "A message for you",
      by: "Southiphon",
    },
    postcard: {
      from: "Southiphon",
      address: ["Teacher Nueng", "the best teacher I know"],
      note: [
        "Thank you for all you",
        "have done for me.",
        "",
        "You will always be my",
        "favourite teacher.",
      ],
      photo: PHOTO_SOUTHIPHON,
    },
  },

  {
    id: 11,
    slug: "eleven",
    prefix: "ANNIE",
    name: "Enny",
    surname: "XIONG",
    colour: "orange",
    seal: "ivory",
    flower: RED_TULIP,
    wish: [
      "Hello Teacher Nueng, I wish you good health. I",
      "hope you succeed in whatever job you apply for,",
      "and that you achieve success in both your career",
      "and love life. May you always have people helping",
      "you in everything you do. May you be free from",
      "worries, anxieties, and sleepless nights.",
      "",
      "You are the best teacher I’ve ever had. You are a",
      "teacher who teaches beyond what we paid for, a",
      "teacher who is truly dedicated to seeing your",
      "students succeed, and a teacher who always",
      "sacrifices personal and family time for your",
      "students. I see your unwavering commitment to",
      "your goal of helping Lao students study abroad",
      "and have better lives because you know how",
      "terrifying poverty is and you don’t want anyone",
      "to experience it. I admire you so much. Even",
      "though you didn’t have the same opportunities as",
      "other children when you were young, you struggled",
      "so much that you managed to study abroad with a",
      "government scholarship. You persevered, saving",
      "money by selling things to buy books and eating",
      "the same egg dishes every day until you",
      "graduated. I don’t know what to say anymore. I",
      "probably could never do what you did because it’s",
      "so difficult and agonizing.",
      "",
      "Thank you for changing my perspective and making",
      "me think more deeply. I feel smarter being with",
      "you. From the first day until now, I haven’t been",
      "disappointed at all in studying with you. I’ve",
      "seen my own progress, especially my voice when",
      "speaking English; it’s gotten so much better that",
      "people around me who hear me speak all say the",
      "same thing: \"Your English is so good! Where do",
      "you study?\" I passed the entrance exam for the",
      "Talented class because of the insights I learned",
      "from you. The interview techniques you taught me,",
      "I applied them and passed. I got into the class I",
      "wanted at Lao American Institute, IC2. You stayed",
      "late to help us solve our problems.",
      "",
      "When I failed the first time, you comforted and",
      "encouraged me, giving me the strength to keep",
      "trying. You never make me feel stupid, you always",
      "taught me that only hard working can get what I",
      "want. I don’t think I’ll ever find a teacher like",
      "you again.",
      "",
      "Finally, I hope you get some rest when you’re",
      "tired.",
    ],
    signed: "Sincerely, Mother Pim of the Nation",
    /* A stand-in, like the others': the song is a placeholder until the real
       one is sent. */
    song: {
      kind: "youtube",
      id: "cL4uhaQ58Rk",
      title: "Lost Stars",
      by: "Adam Levine",
    },
    postcard: {
      from: "Annie",
      address: ["Teacher Nueng", "please get some rest"],
      note: [
        "Thank you so much for",
        "everything you do for us.",
        "",
        "Please take care of",
        "yourself!",
      ],
      photo: PHOTO_ANNIE,
    },
  },

  {
    id: 12,
    slug: "twelve",
    prefix: "BAIFERN",
    name: "Malisa",
    surname: "VAYAKONE",
    colour: "teal",
    seal: "champagne",
    flower: CHRYSANTHEMUM,
    wish: [
      "Happy Teacher’s day 🎊",
      "",
      "ສຸກສັນວັນຄູເດີ້ ທີເຊີ້ໜຶ່ງ 😍 ທີເຊີ້ບໍ່ໄດ້ເປັນແຕ່ຄູ",
      "ແຕ່ທີເຊີ້ຍັງເປັນຄົນຊີ້ນຳທາງ",
      "ໃນອະນະຄົດໃຫ້ນ້ອງໃນຫຼາຍໆເລື່ອງເລີຍ",
      "ບໍ່ວ່າຈະເປັນການຊອກຫາທຶນ ການໃຊ້ຊີວິດ",
      "ການຊອກຫາປະສົບການ",
      "ລວມໄປເຖິງວິທີຫາເງິນຈາກພາສາອັງກິດ",
      "ທີເຊີ້ໃສ່ໃຈນັກຮຽນທຸກຄົນ ຄ່ອຍບອກຄ່ອຍສອນ",
      "ສຸດທ້າຍນີ້ເນື່ອງໃນວັນຄູ ຫຼານຂໍໃຫ້ທີເຊີ້ສຸຂະພາບແຂງແຮງ",
      "ປະສົບຜົນສຳເລັດໃນທຸກໆດ້ານ ມີແຕ່ໂຊກແຕ່ລາບຕົກໃສ່",
      "ແລະທີສຳຄັນຂໍໃຫ້ທີເຊີ້ສຸຂະພາບແຂງແຮງ",
      "ສອນພວກຫຼານໄປເລື້ອຍໆ 🌼",
      "",
      "Thank you for always guiding, supporting, and",
      "inspiring us. Your kindness and dedication mean",
      "so much to us. I’m truly grateful to have you as",
      "my teacher. Wishing you happiness, good health,",
      "and success always💐",
    ],
    signed: "With love, Baifern",
    song: {
      kind: "file",
      src: "/audio/tape-baifern.m4a",
      title: "A message for you",
      by: "Baifern",
    },
    postcard: {
      from: "Baifern",
      address: ["Teacher Nueng", "who guides us all"],
      note: [
        "Thank you for guiding",
        "me, always.",
        "",
        "I’m so lucky to be",
        "your student!",
      ],
      photo: PHOTO_BAIFERN,
    },
  },

  /* The last letter, and the way to the end credits: it holds a ticket to the
     museum where the others hold a cassette. */
  {
    id: 8,
    slug: "eight",
    prefix: "Timmy",
    name: "Visaithat",
    surname: "PHATHITMYXAY",
    colour: "white",
    seal: "yellow",
    flower: BABYS_BREATH,
    holds: [CONTENTS[0], CONTENTS[1], TICKET],
    wish: [
      "I’ve been thinking about how to say this, and",
      "honestly, “thank you” doesn’t feel like enough.",
      "",
      "You were not just my English teacher. You were",
      "one of the people who helped me believe in myself",
      "and gave me the confidence to try things I once",
      "thought were impossible.",
      "",
      "I still remember your advice that encouraged me",
      "to apply for a software developer job. At that",
      "time, I wasn’t sure if I was good enough, but you",
      "helped me become brave enough to try. 😅",
      "",
      "And now, I’m really happy to tell you that I",
      "achieved one of my biggest goals. I received a",
      "fully funded scholarship in Vietnam to study",
      "Artificial Intelligence and Computer Science!",
      "🎓🇻🇳",
      "",
      "I’ve also grown so much along the way. I can now",
      "build my own websites from scratch. For example,",
      "I recently spent a whole month creating this",
      "website with J Anne. It might sound simple, but",
      "for me, it represents how far I’ve come.",
      "",
      "Looking back, I realize that you didn’t just teach",
      "me English. You were the fire that lit my candle,",
      "filling it with motivation, confidence, and the",
      "strength to never give up.",
      "",
      "Thank you for believing in me before I fully",
      "believed in myself.",
      "",
      "I hope that one day, when I become a successful",
      "software developer or AI engineer, I can look back",
      "and say, “Teacher Nueng was one of the people who",
      "helped me become who I am.”",
      "",
      "And don’t worry, I won’t forget my English teacher",
      "when I become famous. 😂",
    ],
    signed: "With love and gratitude, Timmy ❤️",
    postcard: {
      from: "Timmy",
      address: ["Teacher Nueng", "my English teacher"],
      note: [
        "Thank you for everything.",
        "",
        "Don't forget to click the",
        "ticket to visit the End",
        "Credits Museum!",
      ],
      photo: PHOTO_TIMMY,
    },
  },
];

/** Every image the scene needs before it can play its opening. */
export const MAIL_SOURCES: readonly string[] = [
  ENVELOPE.src,
  OPEN_BACK.src,
  OPEN_FRONT.src,
  ...CONTENTS.map((item) => item.src),
  TICKET.src,
  NAME_CARD.src,
  SEAL.src,
  ...LETTERS.map((letter) => letter.flower.src),
  /* Not shown until the envelope is open, but fetched with the rest: it arrives
     as a mask, and a mask that has not loaded is not a blank arrow — it is no
     mask at all, which paints the whole box in ink. */
  ARROW.src,
];
